# Generated by Django 6.0.3 on 2026-03-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deptemp',
            table=None,
        ),
    ]
